package com.crowdlending.constants

class ExperianConstants {
    static final String ACCOUNT_HOLDER_TYPE_INDIVIDUAL = 'Individual'
    static final String ACCOUNT_HOLDER_TYPE_JOINT = 'Joint'
    static final String ACCOUNT_HOLDER_TYPE_AUTHORIZED_USER = 'Authorized User'
    static final String ACCOUNT_HOLDER_TYPE_GURANTOR = 'Guarantor'

    //Account type
    static final String ACCOUNT_TYPE_AUTO_LOAN = 'AUTO LOAN'
    static final String ACCOUNT_TYPE_HOUSING_LOAN = 'HOUSING LOAN'
    static final String ACCOUNT_TYPE_PROPERTY_LOAN = 'PROPERTY LOAN'
    static final String ACCOUNT_TYPE_LOAN_AGAINST_SHARES_SECURITIES = 'LOAN AGAINST SHARES/SECURITIES'
    static final String ACCOUNT_TYPE_PERSONAL_LOAN = 'PERSONAL LOAN'
    static final String ACCOUNT_TYPE_CONSUMER_LOAN = 'CONSUMER LOAN'
    static final String ACCOUNT_TYPE_GOLD_LOAN = 'GOLD LOAN'
    static final String ACCOUNT_TYPE_EDUCATIONAL_LOAN = 'EDUCATIONAL LOAN'
    static final String ACCOUNT_TYPE_LOAN_TO_PROFESSIONAL = 'LOAN TO PROFESSIONAL'
    static final String ACCOUNT_TYPE_CREDIT_CARD = 'CREDIT CARD'
    static final String ACCOUNT_TYPE_LEASING = 'LEASING'
    static final String ACCOUNT_TYPE_OVERDRAFT = 'OVERDRAFT'
    static final String ACCOUNT_TYPE_TWO_WHEELER_LOAN = 'TWO-WHEELER LOAN'
    static final String ACCOUNT_TYPE_NON_FUNDED_CREDIT_FACILITY = 'NON-FUNDED CREDIT FACILITY'
    static final String ACCOUNT_TYPE_LOAN_AGAINST_BANK_DEPOSITS = 'LOAN AGAINST BANK DEPOSITS'
    static final String ACCOUNT_TYPE_FLEET_CARD = 'FLEET CARD'
    static final String ACCOUNT_TYPE_COMMERCIAL_VEHICLE_LOAN = 'Commercial Vehicle Loan'
    static final String ACCOUNT_TYPE_TELCO_WIRELESS = 'Telco – Wireless'
    static final String ACCOUNT_TYPE_TELCO_BROADBAND = 'Telco – Broadband'
    static final String ACCOUNT_TYPE_TELCO_LANDLINE = 'Telco – Landline'
    static final String ACCOUNT_TYPE_SECURED_CREDIT_CARD = 'Secured Credit Card'
    static final String ACCOUNT_TYPE_USED_CAR_LOAN = 'Used Car Loan'
    static final String ACCOUNT_TYPE_CONSTRUCTION_EQUIPMENT_LOAN = 'Construction Equipment Loan'
    static final String ACCOUNT_TYPE_TRACTOR_LOAN = 'Tractor Loan'
    static final String ACCOUNT_TYPE_CORPORATE_CREDIT_CARD = 'Corporate Credit Card'
    static final String ACCOUNT_TYPE_KISAN_CREDIT_CARD = 'Kisan Credit Card'
    static final String ACCOUNT_TYPE_LOAN_ON_CREDIT_CARD = 'Loan on Credit Card'
    static final String ACCOUNT_TYPE_PRIME_MINISTER_JAAN_DHAN_YOJANA_OVERDRAFT = 'Prime Minister Jaan Dhan Yojana - Overdraft'
    static final String ACCOUNT_TYPE_MUDRA_LOANS_SHISHU_KISHOR_TARUN = 'Mudra Loans – Shishu / Kishor / Tarun'
    static final String ACCOUNT_TYPE_MICROFINANCE_OTHERS = 'Microfinance – Others'
    static final String ACCOUNT_TYPE_BUSINESS_LOAN_GENERAL = 'BUSINESS LOAN – GENERAL'
    static final String ACCOUNT_TYPE_BUSINESS_LOAN_PRIORITY_SECTOR_SMALL_BUSINESS = 'BUSINESS LOAN –PRIORITY SECTOR – SMALL BUSINESS'
    static final String ACCOUNT_TYPE_BUSINESS_LOAN_PRIORITY_SECTOR_AGRICULTURE = 'BUSINESS LOAN –PRIORITY SECTOR – AGRICULTURE'
    static final String ACCOUNT_TYPE_BUSINESS_LOAN_PRIORITY_SECTOR_OTHERS = 'BUSINESS LOAN –PRIORITY SECTOR – OTHERS'
    static final String ACCOUNT_TYPE_BUSINESS_NON_FUNDED_CREDIT_FACILITY_GENERAL = 'BUSINESS NON-FUNDED CREDIT FACILITY – GENERAL'
    static final String ACCOUNT_TYPE_BUSINESS_NON_FUNDED_CREDIT_FACILITY_PRIORITY_SECTOR_SMALL_BUSINESS = 'BUSINESS NON-FUNDED CREDIT FACILITY – PRIORITY SECTOR – SMALL BUSINESS'
    static final String ACCOUNT_TYPE_BUSINESS_NON_FUNDED_CREDIT_FACILITY_PRIORITY_SECTOR_AGRICULTURE = 'BUSINESS NON-FUNDED CREDIT FACILITY – PRIORITY SECTOR – AGRICULTURE'
    static final String ACCOUNT_TYPE_BUSINESS_NON_FUNDED_CREDIT_FACILITY_PRIORITY_SECTOR_OTHERS = 'BUSINESS NON-FUNDED CREDIT FACILITY – PRIORITY SECTOR – OTHERS'
    static final String ACCOUNT_TYPE_BUSINESS_LOANS_AGAINST_BANK_DEPOSITS = 'BUSINESS LOANS AGAINST BANK DEPOSITS'
    static final String ACCOUNT_TYPE_STAFF_LOAN = 'Staff Loan'
    static final String ACCOUNT_TYPE_BUSINESS_LOAN_UNSECURED = 'Business Loan - Unsecured'
    static final String ACCOUNT_TYPE_OTHERS = 'Other'

    // Account Status
    static final String ACCOUNT_STATUS_NO_SUIT_FILED = 'No Suit Filed'
    static final String ACCOUNT_STATUS_SUIT_FILED = 'Suit Filed'
    static final String ACCOUNT_STATUS_WILFUL_DEFAULT = 'Wilful default'
    static final String ACCOUNT_STATUS_SUIT_FILED_WILFUL = 'Suit Filed(Wilful default)'
    static final String ACCOUNT_STATUS_WRITTEN_OFF = 'Written-off'
    static final String ACCOUNT_STATUS_RESTRUCTURED = 'Restructured'
    static final String ACCOUNT_STATUS_RESTRUCTURED_LOAN_GOV_MANDATE = 'Restructured Loan (Govt. Mandated)'
    static final String ACCOUNT_STATUS_SETTLED = 'Settled'
    static final String ACCOUNT_STATUS_POST_WO_SETTLED = 'Post (WO) Settled'
    static final String ACCOUNT_STATUS_ACCOUNT_SOLD = 'Account Sold'
    static final String ACCOUNT_STATUS_WRITTEN_OFF_ACCOUNT_SOLD = 'Written Off and Account Sold'
    static final String ACCOUNT_STATUS_ACCOUNT_PURCHASED = 'Account Purchased'
    static final String ACCOUNT_STATUS_ACCOUNT_PURCHASED_AND_WRITTEN_OFF = 'Account Purchased and Written Off'
    static final String ACCOUNT_STATUS_ACCOUNT_PURCHASED_AND_SETTLED = 'Account Purchased and Settled'
    static final String ACCOUNT_STATUS_ACCOUNT_PURCHASED_AND_RESTRUCTURED = 'Account Purchased and Restructured'
    static final String ACCOUNT_STATUS_STATUS_CLEARED = 'Status Cleared'
    static final String ACCOUNT_STATUS_RESTRUCTURED_LOAN = 'Restructured Loan'
    static final String ACCOUNT_STATUS_RESTRUCTURED_LOAN_AND_GOV_MANDATE = 'Restructured Loan (Govt. Mandated)'
    static final String ACCOUNT_STATUS_SUIT_FILED_AND_WRITTEN_OFF = 'Suit Filed and Written-off'
    static final String ACCOUNT_STATUS_SUIT_FILED_AND_SETTLED = 'Suit Filed and Settled'
    static final String ACCOUNT_STATUS_SUIT_FILED_AND_POST_WO_SETTLED = 'Suit Filed and Post (WO) Settled'
    static final String ACCOUNT_STATUS_SUIT_FILED_AND_ACCOUNT_SOLD = 'Suit Filed and Account Sold'
    static final String ACCOUNT_STATUS_SUIT_FILED_AND_WRITTEN_OFF_AND_ACCOUNT_SOLD = 'Suit Filed and Written Off and Account Sold'
    static final String ACCOUNT_STATUS_SUIT_FILED_AND_ACCOUNT_PURCHASED = 'Suit Filed and Account Purchased'
    static final String ACCOUNT_STATUS_FILED_AND_ACCOUNT_PURCHASED_AND_WRITTEN_OFF = 'Suit Filed and Account Purchased and Written Off'
    static final String ACCOUNT_STATUS_FILED_AND_ACCOUNT_PURCHASED_AND_SETTLED = 'Suit Filed and Account Purchased and Settled'
    static final String ACCOUNT_STATUS_FILED_AND_ACCOUNT_PURCHASED_AND_RESTRUCTURED = 'Suit Filed and Account Purchased and Restructured'
    static final String ACCOUNT_STATUS_FILED_AND_STATUS_CLEARED = 'Suit Filed and Status Cleared'
    static final String ACCOUNT_STATUS_WILFUL_DEFAULT_AND_RESTRUCTURED_LOAN = 'Wilful Default and Restructured Loan'
    static final String ACCOUNT_STATUS_WILFUL_DEFAULT_AND_RESTRUCTURED_LOAN_AND_GOV_MANDATE = 'Wilful Default and Restructured Loan (Govt. Mandated)'
    static final String ACCOUNT_STATUS_WILFUL_DEFAULT_SETTLED = 'Wilful Default and Settled'
    static final String ACCOUNT_STATUS_WILFUL_DEFAULT_AND_POST_WO_SETTLED = 'Wilful Default and Post (WO) Settled'
    static final String ACCOUNT_STATUS_WILFUL_DEFAULT_AND_ACCOUNT_SOLD = 'Wilful Default and Account Sold'
    static final String ACCOUNT_STATUS_WILFUL_DEFAULT_AND_WRITTEN_OFF_AND_ACCOUNT_SOLD = 'Wilful Default and Written Off and Account Sold'
    static final String ACCOUNT_STATUS_WILFUL_DEFAULT_AND_ACCOUNT_PURCHASED = 'Wilful Default and Account Purchased'
    static final String ACCOUNT_STATUS_WILFUL_DEFAULT_AND_ACCOUNT_PURCHASED_WRITTEN_OFF = 'Wilful Default and Account Purchased and Written Off'
    static final String ACCOUNT_STATUS_WILFUL_DEFAULT_AND_ACCOUNT_PURCHASED_AND_SETTLED = 'Wilful Default and Account Purchased and Settled'
    static final String ACCOUNT_STATUS_WILFUL_DEFAULT_AND_ACCOUNT_PURCHASED_AND_RESTRUCTURED = 'Wilful Default and Account Purchased and Restructured'
    static final String ACCOUNT_STATUS_WILFUL_DEFAULT_AND_STATUS_CLEARED = 'Wilful Default and Status Cleared'
    static final String ACCOUNT_STATUS_SUIT_FILED_WILFUL_DEFAULT_AND_RESTRUCTURED = 'Suit filed (Wilful default) and Restructured'
    static final String ACCOUNT_STATUS_SUIT_FILED_WILFUL_DEFAULT_AND_GOV_MANDATE = 'Suit filed (Wilful default) and Restructured Loan (Govt. Mandated)'
    static final String ACCOUNT_STATUS_SUIT_FILED_WILFUL_DEFAULT_AND_SETTLED = 'Suit filed (Wilful default) and Settled'
    static final String ACCOUNT_STATUS_SUIT_FILED_WILFUL_DEFAULT_AND_POST_WO_SETTLED = 'Suit filed (Wilful default) and Post (WO) Settled'
    static final String ACCOUNT_STATUS_SUIT_FILED_WILFUL_DEFAULT_AND_ACCOUNT_SOLD = 'Suit filed (Wilful default) and Account Sold'
    static final String ACCOUNT_STATUS_SUIT_FILED_WILFUL_DEFAULT_AND_WRITTEN_OFF_ACCOUNT_SOLD = 'Suit filed (Wilful default) and Written Off and Account Sold'
    static final String ACCOUNT_STATUS_SUIT_FILED_WILFUL_DEFAULT_AND_ACCOUNT_PURCHASED = 'Suit filed (Wilful default) and Account Purchased'
    static final String ACCOUNT_STATUS_SUIT_FILED_WILFUL_DEFAULT_AND_ACCOUNT_PURCHASED_AND_WRITTEN_OFF = 'Suit filed (Wilful default) and Account Purchased and Written Off'
    static final String ACCOUNT_STATUS_SUIT_FILED_WILFUL_DEFAULT_AND_ACCOUNT_PURCHASED_AND_SETTLED = 'Suit filed (Wilful default) and Account Purchased and Settled'
    static final String ACCOUNT_STATUS_SUIT_FILED_WILFUL_DEFAULT_AND_ACCOUNT_PURCHASED_AND_RESTRUCTURED = 'Suit filed (Wilful default) and Account Purchased and Restructured'
    static final String ACCOUNT_STATUS_SUIT_FILED_WILFUL_DEFAULT_AND_STATUS_CLEARED = 'Suit filed (Wilful default) and Status Cleared'
    static final String ACCOUNT_STATUS_CLOSED = 'CLOSED'
    static final String ACCOUNT_STATUS_ACTIVE = 'ACTIVE'

    //Gender Code
    static final String MALE = 'Male'
    static final String FEMALE = 'Female'
    static final String TRANSGENDER = 'Transgender'

    // state code
    static final String JAMMU_KASHMIR = 'JAMMU and KASHMIR'
    static final String HIMACHAL_PRADESH = 'HIMACHAL PRADESH'
    static final String PUNJAB = 'PUNJAB'
    static final String CHANDIGARH = 'CHANDIGARH'
    static final String UTTRANCHAL = 'UTTRANCHAL'
    static final String HARAYANA = 'HARAYANA'
    static final String DELHI = 'DELHI'
    static final String RAJASTHAN = 'RAJASTHAN'
    static final String UTTAR_PRADESH = 'UTTAR PRADESH'
    static final String BIHAR = 'BIHAR'
    static final String SIKKIM = 'SIKKIM'
    static final String ARUNACHAL_PRADESH = 'ARUNACHAL PRADESH'
    static final String NAGALAND = 'NAGALAND'
    static final String MANIPUR = 'MANIPUR'
    static final String MIZORAM = 'MIZORAM'
    static final String TRIPURA = 'TRIPURA'
    static final String MEGHALAYA = 'MEGHALAYA'
    static final String ASSAM = 'ASSAM'
    static final String WEST_BENGAL = 'WEST BENGAL'
    static final String JHARKHAND = 'JHARKHAND'
    static final String ORRISA = 'ORRISA'
    static final String CHHATTISGARH = 'CHHATTISGARH'
    static final String MADHYA_PRADESH = 'MADHYA PRADESH'
    static final String GUJRAT = 'GUJRAT'
    static final String DAMAN_DIU = 'DAMAN and DIU'
    static final String DADARA_NAGAR_HAVELI = 'DADARA and NAGAR HAVELI'
    static final String MAHARASHTRA = 'MAHARASHTRA'
    static final String ANDHRAPRADESH = 'ANDHRA PRADESH'
    static final String KARNATAKA = 'KARNATAKA'
    static final String GOA = 'GOA'
    static final String LAKSHADWEEP = 'LAKSHADWEEP'
    static final String KERALA = 'KERALA'
    static final String TAMIL_NADU = 'TAMIL NADU'
    static final String PONDICHERRY = 'PONDICHERRY'
    static final String ANDAMAN_NICOBAR_ISLANDS = 'ANDAMAN and NICOBAR ISLANDS'
    static final String TELANGANA = 'Telangana'

    //Marital Status
    static final String SINGLE = 'Single'
    static final String MARRIED = 'Married'
    static final String WIDOW = 'Widow/Widower'
    static final String DIVORCED = 'Divorced'

    //Employment Status
    static final String SALARIED = 'Salaried'
    static final String NON_SALARIED = 'Non-Salaried'
    static final String SELF = 'Self-employed'
    static final String PROFESSIONAL = 'Self-employed Professional'
    static final String UNEMPLOYED = 'Unemployed'

    //Telephone Type
    static final String HOME = 'Home Phone'
    static final String OFFICE = 'Office phone'
    static final String UNKNOWN = 'Unknown'
    static final String MOBILE = 'Mobile'

    //Search Type
    static final String AGRI = 'Agriculture Loan'
    static final String AUTO = 'Auto Loan'
    static final String BUSINESS = 'Business Loan'
    static final String COMMERCIAL = 'Commercial Vehicle Loans'
    static final String CONSTRUCTION = 'Construction Equipment loan'
    static final String CONSUMER = 'Consumer Loan'
}
