package com.crowdlending.enums

enum AdminReportPermissionType {

    INVESTMENTS_TAB,
    SYSTEM_STATUS_REPORT_TAB,
    APPLICATION_INTERACTION_REPORT_TAB,
    LENDER_ACTIVITY_REPORT_TAB,
    LOAN_APPLICATION_REPORT_TAB,
    TOTAL_BOOK_SIZE_TAB,
    DISBURSEMENT_MIS_TAB,
    COLLECTION_PRESENTATION_REPORT_TAB,
    LOAN_FEE_REPORT_TAB,
    DELINQUENCY_MIS_REPORT_TAB,
    SANCTION_MIS_REPORT_TAB,
    NACH_PRESENTATION_REPORT_TAB,
    DISBURSEMENT_ENTRY_REPORT_TAB,
    COLLECTION_ENTRY_REPORT_TAB,
    FLDG_REPORT_TAB,
    GROSS_STATISTICS_REPORT_TAB,
    CONSOLIDATED_FLDG_REPORT_TAB,
    MIS_DISBURED_LOANS_TAB,
    MIS_REPAID_LOANS_TAB,
    DAILY_LOAN_DISBURSED_AND_PAID_REPAYMENT_REPORT_TAB,
    CIBIL_REPORT_TAB,
    NACH_REGISTRATION_REPORT_TAB,
    MONTH_WISE_COLLECTION_REPORT_TAB,
    EXPERIAN_REPORT_TAB,
    ADMIN_CRIF_REPORT_TAB,
    ADMIN_EQUIFAX_REPORT_TAB,
    UPCOMING_REPAYMENT_REPORT_TAB,
    MONTH_END_CLOSING_REPORT_TAB,
    ADMIN_RBI_REPORT_TAB,
    AUDIT_LOG_REPORT_TAB,
    QUESTION_ANSWER_REPORT_TAB,
    LOAN_APPLICATION_PARTIAL_REPAYMENT_REPORT_TAB,
    ADMIN_ACCOUNTING_MIS_REPORT_EMI_WISE_TAB




    public static AdminReportPermissionType isValid(String value) {
        return ((value in values()*.toString()) ? (valueOf(value)) : null)

    }
    public static List<AdminReportPermissionType> validPermissions() {
        return this.values()
    }


}