package com.crowdlending.enums


enum BankName {
    ICICI, SBI, KOTAK, YES, YES_CORP, HDFC, AXIS, SYNDICATE, CORPORATION, PNB, UNITED_BANK, INDUSIND, CENTRAL_BANK, CITI,
    DBS, CANARA, STANDARD_CHARTERED, RBL, UNION_BANK, ALLAHABAD, BANK_OF_BARODA, STATE_BANK_PATIALA, STATE_BANK_MYSORE,
    STATE_BANK_TRAVANCORE, TAMILNAD_MERCANTILE, STATE_BANK_BIKANER_JAIPUR, STATE_BANK_HYDERABAD, BANK_OF_INDIA,
    BANK_OF_MAHARASHTRA, BARODA_RAJASTHAN_KSHETRIYA_GRAMIN_BANK, DENA_BANK, INDIAN_BANK, INDIAN_OVERSEAS, ORIENTAL_BANK,
    PUNJAB_SIND, UCO, VIJAYA, IDBI, BANDHAN, CATHOLIC_SYRIAN, CITY_UNION, DHANLAXMI, DCB, FEDERAL, IDFC, KARNATAKA,
    JAMMU_KASHMIR, KARUR_VYASA, LAKSHMI_VILAS, NAINITAL, SOUTH_INDIAN, RBS, SARASWAT_BANK, TJSB, DNB, DNS, DEUTSCHE_BANK,
    GREATER_BOMBAY, APNA_SAHAKARI_BANK, AKHAND_ANAND, ADARSH_CO_OPERATIVE_URBAN_BANK, BASSEIN_CATHOLIC, ANDHRA_BANK,
    AMBERNATH_JAI_HIND_CO_OP_BANK, PUNJAB_MAHARASHTRA_CO_OP_BANK, HSBC, BHARAT, SVC_BANK, SDC, SREENIDHI_SOUHARDA_SAHAKARI_BANK,
    OCEAN_FIRST, CAPITAL_SMALL_FINANCE_BANK_LTD, KALUPUR_COMMERCIAL_CO_OP_BANK, KANGRA_CO_OP_BANK, BHARTIYA_MAHILA_BANK,
    SARDAR_BHILADWALA_PARDI_PEOPLES_CO_OP_BANK, MODEL_CO_OPERATIVE_BANK, MEHSANA_URBAN_CO_OP_BANK, NEW_INDIA_CO_OP_BANK,
    THE_NARODA_NAGRIK_CO_OP_BANK, COSMOS_BANK, JANAKALYAN_SAHAKARI_BANK, JANATA_SAHAKARI_BANK, MJALGAON_JANATA_SAHAKARI_BANK,
    MANVI_PATTANA_SOUHARADA_SAHAKARI_BANK, CENTRAL_CO_OPERATIVE_BANK, NUTAN_NAGARIK_SAHAKARI_BANK, KALYAN_JANATA_SAHAKARI_BANK,
    ABHYUDAYA_CO_OP_BANK, AIRTEL_BANK, EQUITAS_SMALL_FINANCE_BANK, AU_SMALL_FINANCE_BANK, NAGPUR_NAGARIK_SAHAKARI_BANK,
    TEXTILE_CO_OPERATIVE_BANK, JANASEVA_SAHAKARI_BANK, SARASPUR_NAGARIK_CO_OP_BANK, GP_PARSIK_BANK, TGMC_BANK,
    SARVODAYA_SAHAKARI_BANK, SHREE_KADI_NAGARIK_SAHAKARI_BANK, SAURASHTRA_GRAMIN_BANK, ASSOCIATE_CO_OP_BANK,
    SOLAPUR_JANATA_SAHAKARI_BANK, INDRAPRASTHA_SEHKARI_BANK, MAHESH_SAHAKARI_BANK_LTD, PUNE_PEOPLES_CO_OP_BANK,
    VASAI_VIKAS_SAH_BANK_LTD, MAHESH_BANK, UNION_CO_OP_BANK_LTD, JANATHA_SEVA_CO_OP_BANK, The_Wai_Urban_Co_Operative_Bank_Limited,
    The_Vallabh_VidyaNagar_Commercial_Co_Operative_Bank_Ltd, THE_VIJAY_CO_OP_BANK, ZOROASTRIAN_CO_OP_BANK, VAIJAPUR_MARCHANTS_CO_OP_BANK,
    NKGSB_CO_OP_BANK, THE_SUTEX_CO_OP_BANK, THE_SURAT_PEOPLE_CO_OP_BANK_LTD, GUJARAT_AMBUJA_CO_OP_BANK_LTD,
    KANKARIAA_MANINAGAR_NAG_SAH_BANK_LTD, UJJIVAN_SMALL_FINANCE_BANK, CITIZEN_CREDIT_CO_OP_BANK, PADMAVATHI_CO_OP_URBAN_BANK,
    THE_SATARA_SAHAKARI_BANK_LTD, MAHANAGAR_CO_OP_BANK_LTD, SURYODAY_SMALL_FINANCE_BANK_LTD, SHREE_CO_OP_BANK_LTD,
    MANINAGAR_CO_OP_BANK_LTD, THE_VARACHHA_CO_OP_BANK_LTD, SURAT_NATIONAL_CO_OP_BANK_LTD, VIDYA_SAHKARI_BANK_LTD,
    PRERANA_CO_OP_BANK, THE_KARAD_URBAN_CO_OP_BANK_LTD, THE_PANCHSHEEL_MERCANTILE_CO_OP_BANK_LTD, MAGAVEERA_CO_OP_BANK_LTD,
    THANE_BHARAT_SAHAKARI_BANK_LTD, SREE_MAHAYOGI_LAKSHMAMMA_CO_OP_BANK_LTD, VIDARBHA_MERCHANTS_URBAN_CO_OP_BANK_LTD,
    PRATHAMA_BANK, PRIME_BANK, DR_BABASAHEB_AMBEDKAR_MULTISTATE_CO_OP_BANK, The_Hindusthan_Co_Op_Bank_Ltd, KARNAVATI_CO_OP_BANK,
    The_Ahmednagar_Merchant_Co_Op_Bank_Ltd, THE_KANAKAMAHALAKSHMI_CO_OP_BANK_LTD, KURMANCHAL_BANK, The_Gandhidham_CoOperative_Bank_Ltd,
    SHRI_ARIHANT_COOP_BANK, Kallappanna_Awade_Bank, Shivalik_Mercantile_Bank, SAHYDRI_SAHAKARI_BANK, Bihar_Gramin_Bank,
    ANNASAHAB_MAGAR_SAHAKARI_BANK, The_Vishweshwar_Sahakari_Bank_Ltd, PURVANCHAL_BANK, THE_RAJKOT_COMMERCIAL_COOP_BANK,
    The_Jalgaon_Peoples_CoOp_Bank, AHMEDABAD_DISTRICT_CO_OP_BANK, SHIVALIK_MERCANTILE_BANK, The_Akola_District_Central_Co_Op_Bank,
    The_Panipat_Urban_Co_Op_Bank, SHRI_RAJKOT_DISTRICT_CO_OP_BANK, NEELKANT_CO_OP_BANK, The_Eenadu_Co_Op_Urban_Bank,
    The_Ahmedabad_Mercantile_Co_Op_Bank, Adarsh_Co_Operative_Bank_Ltd, Karnataka_Vikas_Grameena_Bank, Noida_Commercial_Co_Op_Bank,
    Jai_Tuljabhavani_Urban_Co_Op_Bank, The_Bardoli_Nagarik_Sahakari_Bank, RMGB, Sterling_Urban_Co_Op_Bank, Smriti_Nagrik_Sahakari_Bank,
    Fino_Payments_Bank, Vaishya_Nagari_Sahakari_Bank, Vananchal_Gramin_Bank, Utkarsh_Small_Finance_Bank, Maharashtra_Gramin_Bank,
    Uttarakhand_Gramin_Bank, Bhagyodaya_Co_Op_Bank, BANK_OF_AMERICA, Manorama_Co_op_Bank_Solapur, Shree_Mahesh_Co_op_Bank_Nashik,
    SANGOLA_URBAN_CO_OPERATIVE_BANK_LTD, Gujarat_State_Co_Op_Bank, Dahod_Urban_Co_Op_Bank, Sanmathi_Sahakari_Bank,
    Jana_Small_Finance_Bank, ADINATH_CO_OP_BANK, Deccan_Merchants_Co_Op_Bank, Seva_Vikas_Co_Op_Bank, Vikas_Sahakari_Bank,
    ABASAHEB_PATIL_RENDAL_SAHAKARI_BANK, SAMATA_SAHAKARI_BANK, Jamia_Co_Op_Bank, Pune_Urban_Co_Op_Bank, The_Sind_Co_Op_Urban_Bank,
    SARVODAYA_COMMERICIAL_CO_OP_BANK, Himachal_Pradesh_State_Co_Op_Bank, KEB_HANA_BANK, SUCO_SOUHARDA_SAHAKARI_BANK,
    ARVIND_SAHAKARI_BANK, Bombay_Mercantile_Co_Op_Bank, RAJARSHI_SHAHU_SAHAKARI_BANK, Nidhi_Co_Op_Bank, URBAN_CO_OP_BANK_BUDAUN

    Object[] getArguments() {
        [] as Object[]
    }

    String[] getCodes() {
        ["${getClass().name}.${name()}"] as String[]
    }

    String getDefaultMessage() {
        name()
    }

    String getEnumValue() {
        return "com.crowdlending.enums.BankName.${this}"
    }
}