package com.crowdlending.enums

enum ExtraPropertyType {

    EMPLOYMENT_TYPE,
    PROFESSION_REGISTRATION_NUMBER,
    MEDICAL_COUNCIL,
    MEMBER_TYPE,
    BRANCH,
    STAMP_DUTY,
    AMOUNT,
    PARTY_TYPE,
    LEGAL_CONSTITUTION,
    ARTICLE_CODE,
    LPG_ID,
    DTH_ID,
    DTH_SERVICE_PROVIDER,
    ELECTRICITY_CONSUMER_NO,
    ELECTRICITY_SERVICE_PROVIDER

}
