package com.crowdlending.enums

enum LayoutThemeSetting {

    HEADER_BACK_GROUND_COLOUR,
    HEADER_BACK_GROUND_COLOUR_FOR_BORROWER,
    HEADER_BACK_GROUND_COLOUR_FOR_INVESTOR,
    HEADER_BACK_GROUND_COLOUR_FOR_TENANT_ADMIN,
    HEADER_BACK_GROUND_COLOUR_FOR_DSA,

    FOOTER_BACK_GROUND_COLOUR,
    FOOTER_BACK_GROUND_COLOUR_FOR_BORROWER,
    FOOTER_BACK_GROUND_COLOUR_FOR_INVESTOR,
    FOOTER_BACK_GROUND_COLOUR_FOR_TENANT_ADMIN,
    FOOTER_BACK_GROUND_COLOUR_FOR_DSA,
    FONT_FAMILY_STYLE,
    PRIMARY_BUTTON_COLOR,
    WARING_BUTTON_COLOR,
    SUCCESS_BUTTON_COLOR,
    DEFAULT_BUTTON_COLOR,
    INFO_BUTTON_COLOR,
    DANGER_BUTTON_COLOR,
    LEFT_MENU_BACKGROUND_COLOR,
    LEFT_MENU_TEXT_COLOR,
    ANCHOR_TEXT_COLOR,
    PAGE_BODY_BACKGROUND_COLOR,
    BOX_HEADER_BACKGROUND_COLOR,
    BOX_BODY_BACKGROUND_COLOR

}