package com.crowdlending.enums

enum UploadDocumentFileType {

    LOAN_FILE,
    LOAN_FILE_CSV,
    LOAN_REPAYMENT_FILE,
    PDC_MANAGEMENT_FILE,
    LOAN_APPLICATION_STATUS_CHANGE_FILE,
    TRANSACTION_STATUS_CHANGE_FILE,
    BORROWER_WITHDRAW_TRANSACTION,
    BORROWER_DEPOSIT_TRANSACTION,
    FUND_TRANSFER_TRANSACTION,
    LOCALIZATION_PROPERTIES_FILE,
    NACH_TRANSACTION_MIS_FILE_1,
    NACH_TRANSACTION_MIS_FILE_2,
    NACH_TRANSACTION_MIS_FILE_3,
    NACH_TRANSACTION_MIS_FILE_4,
    NACH_REGISTRATION_MIS_FILE_1,
    NACH_REGISTRATION_MIS_FILE_2,
    NACH_REGISTRATION_MIS_FILE_3,
    NACH_REGISTRATION_MIS_FILE_4,
    NACH_REGISTRATION_MIS_FILE_5,
    PENALTIES_AND_CHEQUE_BOUNCE_CHARGES_FILE,
    DOCUMENT_CATEGORY_ALIAS,
    UPDATE_LOAN_APPLICATION_GRACE_PERIOD,
    UPDATE_CHEQUE_BOUNCING_CHARGE_AND_PANELTIES_ON_LOAN_REPAYMENT,
    LOCALIZATION_FILE_UPLOAD_EXCEL,
    LOAN_IDENTITY_NUMBERS_FILE,
    LOAN_REFERENCE_DETAILS_FILE,
    LOAN_CO_APPLICANT_DETAILS_FILE,
    LOAN_REPAYMENT_BULK_UPLOAD,
    BORROWER_FILE,
    VIBAN_UPLOAD_FILE,
    PINCODE_UPLOAD_FILE,
    RISK_TYPE_FILE



    public static List<UploadDocumentFileType> fetchValues() {
        List<UploadDocumentFileType> fileTypeList = values()
        fileTypeList.remove(LOCALIZATION_PROPERTIES_FILE)
        return fileTypeList
    }

    public static List<UploadDocumentFileType> fetchBankTransactionUploadFileTypes() {
        return [
                NACH_TRANSACTION_MIS_FILE_1,
                NACH_TRANSACTION_MIS_FILE_2,
                NACH_TRANSACTION_MIS_FILE_3,
                NACH_TRANSACTION_MIS_FILE_4
        ]
    }

    public static List<UploadDocumentFileType> fetchNachRegistrationUploadFileTypes() {
        return [
                NACH_REGISTRATION_MIS_FILE_1,
                NACH_REGISTRATION_MIS_FILE_2,
                NACH_REGISTRATION_MIS_FILE_3,
                NACH_REGISTRATION_MIS_FILE_4,
                NACH_REGISTRATION_MIS_FILE_5,
        ]
    }

}